# Generated by Django 6.0.3 on 2026-03-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='representative',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contract',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('collaborator', 'Cộng tác viên'), ('probation', 'Thử việc'), ('official', 'Chính thức')], max_length=20),
        ),
    ]
