# Generated by Django 6.0.3 on 2026-03-26 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('p1_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('p2_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('p3_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('p3_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('confirmed', 'Đã chốt')], default='draft', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='employees.employee')),
            ],
            options={
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
